from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False,slow_mo=3500)
    page = browser.new_page()
    url = "https://bootswatch.com/default"
    page.goto(url)
    success_btn = page.locator(".btn.btn-outline-success") 
    success_btn.click()
    right_btn = page.locator(".btn.btn-secondary:text-is('Right')")
    right_btn.first.hover()
    input = page.locator("//input[@type='search']").nth(3)
    input.type("Hello",delay=500)
    checkbox = page.locator("id=flexCheckChecked")
    print(checkbox.is_checked())
    switch = page.locator("#flexSwitchCheckDefault")
    switch.set_checked(True)
    switch_1 = page.get_by_label("Checked switch checkbox input")
    switch_1.uncheck()
    password = page.locator("id=floatingInput")
    password.press("KeyP")
    password.press("Shift+KeyD")
    select = page.get_by_label("Example select")
    select.select_option("5")
    multiple = page.locator("id=exampleSelect2")
    multiple.select_option(["1","2","3"])
    file = page.locator("input[id='formFile']")
    file.set_input_files("docs/1.installation.docx")
    btn = page.locator("#btnGroupDrop4")
    btn.click()
    div = page.locator("div[aria-labelledby='btnGroupDrop4']:visible")
    div.locator("a").first.click()

    browser.close()